The GH workflow diff can be skipped

diff --git a/.github/workflows/bazel-diff.yaml b/.github/workflows/bazel-diff.yaml
--- a/.github/workflows/bazel-diff.yaml
+++ b/.github/workflows/bazel-diff.yaml
@@ -1,5 +1,13 @@
 name: bazel-diff
 
+# Docs:
+#
+# Regular build will compute the diff with a previous commit (either from `main` or from the `base` branch in PRs),
+# then it will use bazel-diff tool to find the impacted targets and execute just those tests.
+#
+# If `[skip-diff]` is provided in the commit message it will skip the bazel-diff stuff and just run all the tests.
+
+
 # Controls when the action will run.
 on:
   push:
@@ -40,14 +48,14 @@ jobs:
             librsvg2-dev
 
       - name: Base from base branch (PR)
-        if: ${{ github.event_name == 'pull_request' }}
+        if: ${{ (github.event_name == 'pull_request') && !contains(github.event.head_commit.message, '[skip-diff]') }}
         run: |
           echo "I'm a PR to base '${{ github.event.pull_request.base.ref }}'"
           git fetch origin ${{ github.event.pull_request.base.ref }}
           git worktree add ${{ runner.temp }}/base ${{ github.event.pull_request.base.ref }}
 
       - name: Base from previous commit (not PR)
-        if: ${{ github.event_name == 'push' }}
+        if: ${{ (github.event_name == 'push') && !contains(github.event.head_commit.message, '[skip-diff]') }}
         run: |
           echo "I'm NOT a PR"
           git worktree add ${{ runner.temp }}/base $(git rev-parse HEAD^)
@@ -63,6 +71,7 @@ jobs:
             ${{ runner.os }}-bazel-
 
       - name: Generate hashes from base
+        if: ${{ !contains(github.event.head_commit.message, '[skip-diff]') }}
         run: |
           bazel run $BAZEL_CONFIG //bazel/diff -- generate-hashes --excludeExternalTargets -w ${{ runner.temp }}/base ${{ runner.temp }}/base-hashes.json
           cat ${{ runner.temp }}/base-hashes.json
@@ -71,9 +80,11 @@ jobs:
         run: bazel run $BAZEL_CONFIG //bazel/diff -- generate-hashes --excludeExternalTargets -w ${{ github.workspace }} ${{ runner.temp }}/current-hashes.json
 
       - name: Compute impacted targets
+        if: ${{ !contains(github.event.head_commit.message, '[skip-diff]') }}
         run: bazel run $BAZEL_CONFIG //bazel/diff -- get-impacted-targets -sh ${{ runner.temp }}/base-hashes.json -fh ${{ runner.temp }}/current-hashes.json -o ${{ runner.temp }}/impacted-targets.txt
 
       - name: Save impacted-targets as an artifact
+        if: ${{ !contains(github.event.head_commit.message, '[skip-diff]') }}
         uses: actions/upload-artifact@v4
         with:
           name: impacted-targets.txt
@@ -86,6 +97,7 @@ jobs:
           path: ${{ runner.temp }}/current-hashes.json
 
       - name: Test impacted targets
+        if: ${{ !contains(github.event.head_commit.message, '[skip-diff]') }}
         run: |
           impacted_targets=()
           IFS=$'\n' read -d '' -r -a impacted_targets < ${{ runner.temp }}/impacted-targets.txt || true
@@ -98,6 +110,17 @@ jobs:
           set +e
           # Run all the tests (except manual ones)
           bazel test $BAZEL_CONFIG --test_tag_filters=-manual $one_liner
+
+          # error_code 4 - Build successful but no tests were found even though testing was requested (https://bazel.build/run/scripts)
+          err=$? ; if (( $err != 4 )) ; then exit $err ; fi
+
+      - name: Test impacted targets
+        if: ${{ contains(github.event.head_commit.message, '[skip-diff]') }}
+        run: |
+          # Do not fail for next command
+          set +e
+          # Run all the tests (except manual ones)
+          bazel test $BAZEL_CONFIG --test_tag_filters=-manual //...
 
           # error_code 4 - Build successful but no tests were found even though testing was requested (https://bazel.build/run/scripts)
           err=$? ; if (( $err != 4 )) ; then exit $err ; fi
